config/routes.rb
Rails.application.routes.draw do
  get 'say/hello'
  get 'say/goodbye'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
    @time = Time.now #Setting time value into an instance variable called @time 
  end

  def goodbye
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/say/goodbye.html.erb
<h1> Goodbye from rails! </h1>


<p> 
  Goodbye it was nice having you here! 
</p>

<p>
  Say <a href="/say/hello"> hello! </a>
</p>

<p>
  Say <%= link_to "hello", say_hello_path %> again.
</p>

app/views/say/hello.html.erb
<h1>Hello from Rails!</h1>


<p> 
  It is now  <%= @time %> <!-- Using instance variable to substitute the time into the output !-->
</p>

<p>
  Say <a href="/say/goodbye"> Goodbye! </a>
</p>

<p>
  Time to say
  <%= link_to "Goodbye" , say_goodbye_path %>! 







<!-- line 5 showing that communication between the controller and the view was successful,
Reasoning for this we may want to localize a users time zone by setting it in the controller/ time is data should be supplied to view from controller !--> 
<!-- Line 6:  Theres a link_to() call within ERB sequence, The first parameter in the call to link_to() is the text to be displayed in the hyperlink, and the next parameter tells Rails to generate the link to the goodbye() action. !-->